### ISSUE TITLE
Not installing due to 404

### ISSUE THREAD

**Issue by tsirolnik** [zeevl/phantomjs2#16]
Well, it's pretty simple and straightforward - 
Version 2.0.0 doesn't exist in bitbucket.org/ariya/phantomjs/downloads this results in a 404 error in npm and with a failure of the installation.

**Comment by albatrosary** [comment]
Hi.

I also use the PhantomJS2, it made a similar error in Travis.
Reason same thing.

Thank you.

**Comment by tsirolnik** [comment]
No problem :)

**Comment by zeevl** [comment]
fixed with https://github.com/zeevl/phantomjs2/pull/13
